=== datakaveri/data-quality-assessment/schemas/schema_BikeDocking.json
{
"$id": "smartbikemobility.com/bfc54d46ca3cf5dac6eaef7b42f8fc87f94a812b/rs.iudx.org.in/chennai-bike-docking-locations/station-locations",
"$schema": "https://json-schema.org/draft/2020-12/schema",
"title": "Location of Smart Bike Docking Stations in Chennai City",
"type": "object",
"properties": {
	"name": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "location": {
        "type": "object",
        "properties": {
          "coordinates": {
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "coordinates",
          "type"
        ]
      },
      "stationName": {
        "type": "string"
      }
},
"additionalProperties":false,
"required": [
    "name",
    "id",
    "location",
    "stationName"
]
}

=== datakaveri/data-quality-assessment/data/ChennaiBikeDock_Data_2023/chennaiBikeDockingStation.json
[{"name": "Bike Docking Station Abusali Street GCC Park opp R5 Police Station", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.199119, 13.049899], "type": "Point"}, "stationName": "Abusali Street GCC Park opp R5 Police Station"}, {"name": "Bike Docking Station Acropolis", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.260317, 13.04517], "type": "Point"}, "stationName": "Acropolis"}, {"name": "Bike Docking Station AG DMS Metro", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.248516, 13.046229], "type": "Point"}, "stationName": "AG DMS Metro"}, {"name": "Bike Docking Station AGS Theatre - GN Chetty Road", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.245193, 13.047747], "type": "Point"}, "stationName": "AGS Theatre - GN Chetty Road"}, {"name": "Bike Docking Station Alandur Metro", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2010611, 13.0035349], "type": "Point"}, "stationName": "Alandur Metro"}, {"name": "Bike Docking Station Amma Arangam (Ware House)", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.219737, 13.082432], "type": "Point"}, "stationName": "Amma Arangam (Ware House)"}, {"name": "Bike Docking Station Anna Centenary Library", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.24069, 13.01701], "type": "Point"}, "stationName": "Anna Centenary Library"}, {"name": "Bike Docking Station Anna Nagar 18th Main Road", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.200507, 13.094631], "type": "Point"}, "stationName": "Anna Nagar 18th Main Road"}, {"name": "Bike Docking Station Anna Nagar 21st Main Road", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2064, 13.09123], "type": "Point"}, "stationName": "Anna Nagar 21st Main Road"}, {"name": "Bike Docking Station Anna Nagar East \u2013 Metro Station", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.219333, 13.084387], "type": "Point"}, "stationName": "Anna Nagar East \u2013 Metro Station"}, {"name": "Bike Docking Station Anna Nagar Tower Park - Feeder", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.21303, 13.0866], "type": "Point"}, "stationName": "Anna Nagar Tower Park - Feeder"}, {"name": "Bike Docking Station Anna Nagar, K Block, Opp. Nilgiris", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.22368, 13.091091], "type": "Point"}, "stationName": "Anna Nagar, K Block, Opp. Nilgiris"}, {"name": "Bike Docking Station Arumbakkam Metro", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.211372, 13.061584], "type": "Point"}, "stationName": "Arumbakkam Metro"}, {"name": "Bike Docking Station ASV Chandilya Tower- Thuraipakkam", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.23173, 12.93155], "type": "Point"}, "stationName": "ASV Chandilya Tower- Thuraipakkam"}, {"name": "Bike Docking Station Besant Nagar Rajaji Bavan", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.26851, 13.00276], "type": "Point"}, "stationName": "Besant Nagar Rajaji Bavan"}, {"name": "Bike Docking Station Besant Nagar-Govt. Staff Quarters", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.26704, 12.99949], "type": "Point"}, "stationName": "Besant Nagar-Govt. Staff Quarters"}, {"name": "Bike Docking Station Boat Club Road", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.251545, 13.027666], "type": "Point"}, "stationName": "Boat Club Road"}, {"name": "Bike Docking Station Bouganvillea Park Anna Nagar East - Feeder", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.22086, 13.09215], "type": "Point"}, "stationName": "Bouganvillea Park Anna Nagar East - Feeder"}, {"name": "Bike Docking Station C.S.I. Kalyani Multispeciality Hospital", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.273, 13.043529], "type": "Point"}, "stationName": "C.S.I. Kalyani Multispeciality Hospital"}, {"name": "Bike Docking Station CMS-Pantheon Road - Egmore", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.264987, 13.076039], "type": "Point"}, "stationName": "CMS-Pantheon Road - Egmore"}, {"name": "Bike Docking Station Crescent Ground", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.22009, 13.08097], "type": "Point"}, "stationName": "Crescent Ground"}, {"name": "Bike Docking Station DR.MGR Janaki College, Adyar", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2597, 13.0159], "type": "Point"}, "stationName": "DR.MGR Janaki College, Adyar"}, {"name": "Bike Docking Station Egmore Metro", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.261641, 13.079453], "type": "Point"}, "stationName": "Egmore Metro"}, {"name": "Bike Docking Station Ekkatuthangal Metro", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2053988, 13.01683], "type": "Point"}, "stationName": "Ekkatuthangal Metro"}, {"name": "Bike Docking Station Five Furlong Road Velachery", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2158165, 12.9979039], "type": "Point"}, "stationName": "Five Furlong Road Velachery"}, {"name": "Bike Docking Station Foot Over Bridge Karapakkam", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2330756, 12.9337522], "type": "Point"}, "stationName": "Foot Over Bridge Karapakkam"}, {"name": "Bike Docking Station Foot Over Bridge Ushera Residences, Chemmanchery", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.227103, 12.876967], "type": "Point"}, "stationName": "Foot Over Bridge Ushera Residences, Chemmanchery"}, {"name": "Bike Docking Station GCC Multi Level Parking Pondy Bazar", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.239792, 13.040392], "type": "Point"}, "stationName": "GCC Multi Level Parking Pondy Bazar"}, {"name": "Bike Docking Station GCC Park Porur", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.168246, 13.029819], "type": "Point"}, "stationName": "GCC Park Porur"}, {"name": "Bike Docking Station GCC Rippon Building", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.271195, 13.08305], "type": "Point"}, "stationName": "GCC Rippon Building"}, {"name": "Bike Docking Station GCC Zone 4 - Tondiarpet", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.286489, 13.1210289], "type": "Point"}, "stationName": "GCC Zone 4 - Tondiarpet"}, {"name": "Bike Docking Station GCC Zone 5 Office - Near Basin Bridge", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.274709, 13.104479], "type": "Point"}, "stationName": "GCC Zone 5 Office - Near Basin Bridge"}, {"name": "Bike Docking Station Greater Chennai Corporation - Zone 13 Adayar", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2572022, 13.0053297], "type": "Point"}, "stationName": "Greater Chennai Corporation - Zone 13 Adayar"}, {"name": "Bike Docking Station Greater Chennai Corporation Park - Zone 13 Adayar", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2558722, 12.9948371], "type": "Point"}, "stationName": "Greater Chennai Corporation Park - Zone 13 Adayar"}, {"name": "Bike Docking Station Greater Chennai Corporation Park OMR(Tecci Park)", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.228592, 12.91046], "type": "Point"}, "stationName": "Greater Chennai Corporation Park OMR(Tecci Park)"}, {"name": "Bike Docking Station Greater Chennai Corporation Zone 13 Unit 38 Thiruvanmiyur", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.25769, 12.9846], "type": "Point"}, "stationName": "Greater Chennai Corporation Zone 13 Unit 38 Thiruvanmiyur"}, {"name": "Bike Docking Station Greenways MRTS", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2529244, 13.0210733], "type": "Point"}, "stationName": "Greenways MRTS"}, {"name": "Bike Docking Station Harleys Road Kilpauk, Opp to Indian Bank", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.242151, 13.082823], "type": "Point"}, "stationName": "Harleys Road Kilpauk, Opp to Indian Bank"}, {"name": "Bike Docking Station Harrington Road", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.2372766, 13.0692792], "type": "Point"}, "stationName": "Harrington Road"}, {"name": "Bike Docking Station Independence park nanganallur", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.186183, 12.980832], "type": "Point"}, "stationName": "Independence park nanganallur"}, {"name": "Bike Docking Station Indira Nagar MRTS", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.249537, 12.996176], "type": "Point"}, "stationName": "Indira Nagar MRTS"}, {"name": "Bike Docking Station Infoview Karapakkam", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.229172, 12.915149], "type": "Point"}, "stationName": "Infoview Karapakkam"}, {"name": "Bike Docking Station Jeeva Park - GN Chetty Road", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.23765, 13.04379], "type": "Point"}, "stationName": "Jeeva Park - GN Chetty Road"}, {"name": "Bike Docking Station Kandaswamy College - Feeder", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9", "location": {"coordinates": [80.21813, 13.08598], "type": "Point"}, "stationName": "Kandaswamy College - Feeder"}, {"name": "Bike Docking Station Kasturba Nagar MRTS", "id": "953729d0-16d9-4878-bf16-c1e23d024ba9
